version: 2.1
orbs:
  node: circleci/node@4.1.0
  npm-publisher: uraway/npm-publisher@0.2.0

jobs:
  test:
    description: Run all tests
    executor:
      name: node/default
      tag: '14.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Run jest tests'
          command: yarn run test -w=2

workflows:
  deploy:
    jobs:
      - test
      - hold:
          filters:
            branches:
              only: main
          type: approval
          requires:
            - test
      - npm-publisher/publish-from-package-version:
          name: publish_to_npm
          requires:
            - hold
          filters:
            branches:
              only: main
          ssh-fingerprints: 39:57:46:4f:6f:eb:d9:3f:75:f4:1d:3b:fa:ab:d6:71
          pre-publish-steps:
            - run: yarn install
          publish-token-variable: NPM_TOKEN
